url=https://www.urbanladder.com/
browser=chrome
implicitWait=10
screenshotPath=./screenshots/
outOfStockBookshelvesUrl=https://www.urbanladder.com/collection/bookshelves?is_available=false

# ---------- Valid Data ----------
firstname=Ritesh
lastname=Deshpande
email=ritesh@gmail.com
mobile=9876543210
message=Happy Birthday! Enjoy your gift

# ---------- Invalid Data ----------
invalidEmail=riteshgmail.com
invalidMobile=12345
invalidMessage=Invalid test data